name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # main 브랜치에 push되었을 때 실행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install
        working-directory: ./frontend  # frontend 디렉토리에서 실행

      - name: Create .env.local and set environment variables  # .env.local 파일 생성 및 환경변수 추가
        run: |
          touch .env.local  # .env.local 파일 생성
          echo "ENTRY_POINT=${{ secrets.ENTRY_POINT }}" >> .env.local
          echo "REACT_APP_PASSWORD=${{ secrets.REACT_APP_PASSWORD }}" >> .env.local
        working-directory: ./frontend  # frontend 디렉토리에서 실행

      - name: Build the project
        run: npm run build:dev 
        working-directory: ./frontend  # frontend 디렉토리에서 실행

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ./frontend/.build  # 빌드된 파일이 위치한 디렉토리
          publish_branch: release  # 배포할 브랜치
