name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 체크아웃 리포지토리
      - name: Checkout repository
        uses: actions/checkout@v2

      # 2. 프론트엔드 디렉토리로 이동 후 빌드
      - name: Build Frontend
        working-directory: frontend
        run: |
          npm install
          npm run build:dev

      # 3. 백엔드 디렉토리로 이동 후 빌드
      - name: Build Backend
        working-directory: backend
        run: |
          npm install
          npm run build

      # 4. 프론트엔드 빌드 결과물을 백엔드에 복사
      - name: Copy Frontend Build to Backend
        run: |
          cp -r frontend/.build/* backend/.build/

      # 5. 백엔드 실행
      - name: Start Backend
        working-directory: backend
        run: npm run start
